---
module: "andrewwormald"
service:
  name: "apollo"
  logicals:
    - name: "users"
      api:
        fileName: "api.go"
        interface: "API"
        implementations:
          local: true
          http: true
    - name: "bookings"
      api:
        fileName: "api.go"
        interface: "Client"
        implementations:
          local: true
          http: true
      dependencies:
        - name: "Users"
          path: "andrewwormald/apollo/users"
          type: "users.API"
        - name: "MainDB"
          path: "database/sql"
          type: "*sql.DB"

